// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// Comic Loader 
export const COMIC_ENABLE_LOADER = 'COMIC_ENABLE_LOADER';
export const COMIC_DISABLE_LOADER = 'COMIC_DISABLE_LOADER';
//Bookmark

export const BOOKMARK_ENABLE_LOADER = 'BOOKMARK_ENABLE_LOADER';
export const BOOKMARK_DISABLE_LOADER = 'BOOKMARK_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const USER_BOOKMARK = 'USER_BOOKMARK'
export const SET_COVER = 'USER_COVER';
export const LIST_POST = 'LIST_POST';
export const LIST_POST_REQUEST = 'LIST_POST_REQUEST';
export const DELETE_LIST_POST = 'DELETE_LIST_POST';


//Load Comic 
export const COMIC_LIST_REQUEST = 'COMIC_LIST_REQUEST';
export const COMIC_LIST_RESPONSE = 'COMIC_LIST_RESPONSE';
export const COMIC_LOADING_ENDED = 'COMIC_LOADING_ENDED';
export const COMIC_LOAD_FAILED = 'COMIC_LOAD_FAILED';
export const COMIC_CLEAR_LIST = 'COMIC_LOAD_FAILED';

//info Comic 
export const COMIC_INFO_REQUEST = 'COMIC_INFO_REQUEST';
export const COMIC_INFO_RESPONSE = 'COMIC_INFO_RESPONSE';
export const COMIC_INFO_LOADING_ENDED = 'COMIC_INFO_LOADING_ENDED';
export const COMIC_INFO_LOAD_FAILED = 'COMIC_INFO_LOAD_FAILED';
export const COMIC_INFO_CLEAR_LIST = 'COMIC_INFO_LOAD_FAILED';

//ChapterComic 
export const CHAPTER_LIST_REQUEST = 'CHAPTER_INFO_REQUEST';
export const CHAPTER_LIST_RESPONSE = 'CHAPTER_INFO_RESPONSE';
export const CHAPTER_LIST_LOADING_ENDED = 'CHAPTER_INFO_LOADING_ENDED';
export const CHAPTER_LIST_LOAD_FAILED = 'CHAPTER_INFO_LOAD_FAILED';
export const CHAPTER_LIST_CLEAR_LIST = 'CHAPTER_INFO_LOAD_FAILED';

//search comic 

export const COMIC_SEARCH_REQUEST = 'COMIC_SEARCH_REQUEST';
export const COMIC_SEARCH_RESPONSE = 'COMIC_SEARCH_RESPONSE';
export const COMIC_SEARCH_LOADING_ENDED = 'COMIC_SEARCH_LOADING_ENDED';
export const COMIC_SEARCH_FAILED = 'COMIC_SEARCH_LOAD_FAILED';
export const COMIC_SEARCH_CLEAR_LIST = 'COMIC_SEARCH_LOAD_FAILED';

// List bookmark

export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_RESPONSE = 'BOOKMARK_LIST_RESPONSE';
export const BOOKMARK_LOADING_ENDED = 'BOOKMARK_LOADING_ENDED';
export const BOOKMARK_LOAD_FAILED = 'BOOKMARK_LOAD_FAILED';
export const BOOKMARK_CLEAR_LIST = 'BOOKMARK_LOAD_FAILED';


// User 
export const  HISTORY_START_LOAD = 'HISTORY_START_LOAD'
export const  HISTORY_COMIC = 'HISTORY_COMIC'
export const  HISTORY_END_LOAD = 'HISTORY_END_LOAD'

//create 
export const  CREATE_USER = 'CREATE_USER'
export const  USER_RESPONSE = 'USER_RESPONSE'
